### ISSUE TITLE
Recent demos cannot be processed anymore: CL_ParseServerMessage: Unknown cmd type

### ISSUE THREAD

**Issue by tcsabina** [deurk/mvdparser#1]
I saw some discussion on Discord about this. Something to do with BigCoords, whatever that should mean...

Would be nice to bring this tool back to life.

**Comment by clayg** [comment]
Does anyone have an example of a `.mvd` demo that failures with error?

**Comment by deurk** [comment]
Did you get one @clayg ?

**Comment by fzwoch** [comment]
I think any server with `sv_bigcoords 1` should create such demos.

E.g. https://www.quakeservers.net/quakeworld/server_status/3593/ it seems to be listed in the status aswell.

**Comment by bleader** [comment]
I'm afraid that there are other things, for testing I hardcoded some things:
- replaced the return on unknown cmd by a break so we keep processing
- hardcoded `MSG_ReadCoord()` and `MSG_ReadAngle()` to work like `msg_coordsize = 4` and `msg_anglesize = 2`

It does process the whole demo, and info logged seem to be accurate, but there still are a lot of `CL_ParseServerMessage: Unknown cmd type.` error messages. I guess there are other format that may be different.

**Comment by fzwoch** [comment]
Perhaps it is worth checking out:

https://github.com/jogi1/mvd_parser_lib

**Comment by bleader** [comment]
> Perhaps it is worth checking out:
> 
> https://github.com/jogi1/mvd_parser_lib

As far as I can tell, the functions `MVD_MSG_ReadCoord()` and `MVD_MSG_ReadAngle()` are the same as in mvdparser, aka: the old version not handling bigcoords.

**Comment by clayg** [comment]
@fzwoch I used the server you suggested and created a demo, it's available here:

https://drive.google.com/file/d/1wY_TKulS8cOJaAwAPGYqxVg7hYUMEgpS/view?usp=sharing

@bleader for me when I tried to process this demo I got this error:
```
clayg@banana:~/quake/mvdparser$ ./mvdparser test.mvd
CL_ParseServerMessage: Unknown cmd type.
MVD_Parser_StartParse: Failed to parse server message.
```

**Comment by fzwoch** [comment]
Jogi's parser in Go seems to handle is just fine. So if there is extra code required one should be able to find it there.

Here is the sample output for that `test.mvd`:

```json
{
	"hostname": "KTX #1 @ nicotinelounge.com",
	"map_name": "Smile, It Gets Worse",
	"map_file": "maps/ztndm1.bsp",
	"players": [
		{
			"name_sanatized": "OldDevel",
			"name_int": "79 108 100 68 101 118 101 108",
			"team_sanatized": "",
			"team_int": "",
			"frags": "2",
			"deaths": "24",
			"Suicides": "0",
			"itemstats": {"Axe":{"Damage":0,"Drop":0,"Pickup":0},"GreenArmor":{"Damage_Absorbed":0,"Pickup":7},"GrenadeLauncher":{"Damage":0,"Drop":8,"Pickup":8},"LightningGun":{"Damage":0,"Drop":13,"Pickup":13},"MegaHealth":{"Drop":0,"Pickup":2},"NailGun":{"Damage":0,"Drop":1,"Pickup":1},"Pentagram":{"Drop":0,"Pickup":0},"Quad":{"Drop":0,"Pickup":0},"RedArmor":{"Damage_Absorbed":0,"Pickup":12},"Ring":{"Drop":0,"Pickup":0},"RocketLauncher":{"Damage":0,"Drop":12,"Pickup":13},"Shotgun":{"Damage":0,"Drop":0,"Pickup":0},"SuperNailGun":{"Damage":0,"Drop":11,"Pickup":11},"SuperShotgun":{"Damage":0,"Drop":13,"Pickup":14},"YellowArmor":{"Damage_Absorbed":0,"Pickup":0}}
		},
		{
			"name_sanatized": "/ bro",
			"name_int": "47 32 98 114 111",
			"team_sanatized": "blue",
			"team_int": "98 108 117 101",
			"frags": "24",
			"deaths": "2",
			"Suicides": "0",
			"itemstats": {"Axe":{"Damage":0,"Drop":0,"Pickup":0},"GreenArmor":{"Damage_Absorbed":0,"Pickup":4},"GrenadeLauncher":{"Damage":0,"Drop":3,"Pickup":4},"LightningGun":{"Damage":0,"Drop":3,"Pickup":4},"MegaHealth":{"Drop":0,"Pickup":9},"NailGun":{"Damage":0,"Drop":2,"Pickup":3},"Pentagram":{"Drop":0,"Pickup":0},"Quad":{"Drop":0,"Pickup":0},"RedArmor":{"Damage_Absorbed":0,"Pickup":0},"Ring":{"Drop":0,"Pickup":0},"RocketLauncher":{"Damage":0,"Drop":3,"Pickup":4},"Shotgun":{"Damage":0,"Drop":0,"Pickup":0},"SuperNailGun":{"Damage":0,"Drop":3,"Pickup":4},"SuperShotgun":{"Damage":0,"Drop":3,"Pickup":3},"YellowArmor":{"Damage_Absorbed":0,"Pickup":6}}
		}
	]
}
```

**Comment by d2-d2** [comment]
Jogi's version is also buggy. It's not counting frags/deaths properly. I have reported this via discord. Waiting for response :P

**Comment by meag** [comment]
Fix should be included in https://github.com/deurk/mvdparser/pull/4

**Comment by tcsabina** [comment]
Closing, as it has been fixed
